apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: goo-space-developer
  namespace: default
subjects:
- kind: Group
  name: goo
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: space-developer
