apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-space-developer
  namespace: default
subjects:
- kind: User
  name: oidc:alice@vcap.me
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: space-developer
