---
apiVersion: v1
kind: Namespace
metadata:
  name: mcc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi-cluster-controller
  name: multi-cluster-controller
  namespace: mcc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-cluster-controller
  template:
    metadata:
      labels:
        app: multi-cluster-controller
    spec:
      serviceAccountName: multi-cluster-controller
      containers:
      - image: eirini/multi-cluster-controller:dev
        imagePullPolicy: IfNotPresent
        name: mcc
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
        command: ["/usr/local/bin/multicluster-controller"]
      volumes:
      - name: kubeconfig
        configMap:
          name: kubeconfig

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: multi-cluster-controller
  name: multi-cluster-controller
  namespace: mcc
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-cluster-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-cluster-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-cluster-controller
subjects:
- kind: ServiceAccount
  name: multi-cluster-controller
  namespace: mcc

