---
kind: Org
apiVersion: code.cloudfoundy.org.org/v1
metadata:
  name: org1
spec:
  spaces:
  - name: space1
    cluster_name: cross-org-1
    users:
    - name: "alice"
      roles: ["cf-space-developer"]
  - name: space2
    cluster_name: cross-org-1
    users:
    - name: "bob"
      roles: ["cf-space-developer"]
  users:
  - name: "will"
    roles: ["cf-org-manager"]
---
kind: Org
apiVersion: code.cloudfoundy.org.org/v1
metadata:
  name: org2
spec:
  spaces:
  - name: space1
    cluster_name: cross-org-1
    users:
    - name: "alice"
      roles: ["cf-space-developer"]
  users:
  - name: "andy"
    roles: ["cf-org-manager"]
---
kind: GlobalUser
apiVersion: code.cloudfoundy.org.org/v1
metadata:
  name: superuser
spec:
  roles: ["cf-admin"]
