---
kind: Org
apiVersion: code.cloudfoundy.org.org/v1
metadata:
  name: alice-org
  namespace: org
spec:
  clusters:
  - name: "cross-org-1"
    namespaces: ["alice-1", "alice-2"]
  users: ["alice"]
---
kind: Org
apiVersion: code.cloudfoundy.org.org/v1
metadata:
  name: bob-org
  namespace: org
spec:
  clusters:
  - name: "cross-org-1"
    namespaces: ["bob-1"]
  - name: "cross-org-2"
    namespaces: ["bob-2"]
  users: ["bob"]
