---
kind: Org
apiVersion: code.cloudfoundy.org.org/v1
metadata:
  name: org1
  namespace: org
spec:
  spaces:
  - name: space1
    cluster_name: cross-org-1
    users:
    - name: "alice"
      roles: ["space-developer"]
  - name: space2
    cluster_name: cross-org-1
    users:
    - name: "bob"
      roles: ["space-developer"]
  users:
  - name: "will"
    roles: ["org-manager"]
---
kind: Org
apiVersion: code.cloudfoundy.org.org/v1
metadata:
  name: org2
  namespace: org
spec:
  spaces:
  - name: space1
    cluster_name: cross-org-1
    users:
    - name: "alice"
      roles: ["space-developer"]
  users:
  - name: "andy"
    roles: ["org-manager"]
