#@data/values
---
#! UAA Deployment Values
version: ""
image: ""
namespace: default
labels:
  instance: standalone
  partOf: uaa
  managedBy: kubectl

resources:
  uaa:
    requests:
      memory: 512Mi
      cpu: 50m
    limits:
      memory: 2000Mi
      cpu: 500m
  statsd_exporter:
    requests:
      memory: 10Mi
      cpu: 10m
    limits:
      memory: 100Mi
      cpu: 100m

issuer:
  uri: https://172.17.0.1.nip.io

tomcat:
  accessLoggingEnabled: "y"

#! Statsd Deployment Values
images:
  statsd_exporter: cloudfoundry/statsd_exporter:v0.15.0@sha256:10a64dc4ad0a3e3fe88372f0481dea5c02595c38d168617836a99a649d3ac407


#! UAA Application Values
database:
  scheme: hsqldb
  username: ~
  password: ~
  url: "jdbc:hsqldb:mem:uaa"

jwt:
  policy:
    activeKeyId: active-key-id
    keys:
      active-key-id:
        signingKey: |
          <redacted rsa private key>

login:
  saml:
    activeKeyId: active-key-id
    keys:
      active-key-id:
        key: |
          <redacted rsa private key>
        passphrase: passphrase
        certificate: |
          <redacted certificate>

encryption:
  active_key_label: active-key-label
  encryption_keys:
    - label: active-key-label
      passphrase: foobar12

smtp:
  host: ~
  port: 25
  user: ~
  password: ~
  starttls: ~
  from_address: ~

admin:
  client_secret: client

#! ca_certs should be an array of PEM-encoded certs
#! These will be added to the UAA's truststore
ca_certs: []

automountServiceAccountToken: false
