apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-space-developer
  namespace: federate-me
subjects:
- kind: User
  name: alice
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cf-space-developer
