apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dave-admin
  namespace: cf
subjects:
- kind: User
  name: dave
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cf-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dave-global-subnamespace-manager
  namespace: cf
  annotations:
    propagate.hnc.x-k8s.io/select: "cloudfoundry.org/org=true"
subjects:
- kind: User
  name: dave
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cf-space-manager
